# Generated by Django 4.1.2 on 2022-10-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchlist',
            new_name='content',
        ),
    ]
